### ISSUE TITLE
Missing License File?

### ISSUE THREAD

**Issue by nicholascross** [chillok/SimpleCollectionViewPointGraph#1]
Hi, I was wondering what the restrictions on reuse of this code are?  But I couldn't see the license file.

**Comment by chillok** [comment]
Hey there,

I never really expected anyone to take notice of these - hence didn't bother with the license. Feel free to use it in any way you see fit, I'd love to see a link to your work once it's done btw =)

There is one caveat with the code base here though. I called it 'BezierPath', there is even a file called 'BezierPath', however it doesn't actually use a BezierPath. It just uses some simple core graphics. I had some trouble with drawing to the BezierPath. I never bothered to rename it for the reason I mentioned above! 

I might have some free time later I'll update with license and rename it I get a chance.

Cillian

**Comment by nicholascross** [comment]
Great and thanks!

I was thinking it might make a nice extra feature in a side project of mine, I will let you know if I end up finishing it... you know how these things are :)
